---
# tasks file for dadjokes
- name: Ensure group "gpgroup" exists
  group:
    name: gpgroup
    state: present

- name: Add the user "gpuser"  
  user:
    name: gpuser
    state: present
    comment: General Purpose User
    group: gpgroup

- name: Add go to .profile for gpuser
  copy: 
    src: gpuser_profile
    dest: /home/gpuser/.profile

- name: download golang
  get_url:
    url: https://dl.google.com/go/go1.19.3.linux-amd64.tar.gz
    dest: /tmp/go1.19.3.linux-amd64.tar.gz
    
- name: install golang
  unarchive:
    src: /tmp/go1.19.3.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Deploy env file
  copy: 
    src: ../../../.env
    dest: /home/gpuser/gocode/.env
    owner: gpuser
    group: gpgroup
    mode: '0400'

- name: create code dir
  file: 
    name: /home/gpuser/gocode
    state: directory
    owner: gpuser
    group: gpgroup
    mode: '0544'

- name: deploy go code
  copy: 
    src: ../../../main
    dest: /home/gpuser/gocode
    owner: gpuser
    group: gpgroup
    mode: '0544'

- name: create cronjob
  cron:
    name: "a job for reboot"
    weekday: "*"
    minute: "42"
    hour: "10"
    user: gpuser
    job: "/home/gpuser/gocode/main > /tmp/main.log"

# Next add go installation
# add go code to files dir and add ansible to deploy go code to the vm
# run whatever shell commands you need to run to ensure go works and modules work
# figure out how to export your TWILIO env vars without exposing them
# then once everything is in place, try to run go program on the vm manually, does it work?
# then figure out how to send to more than one phone number
# then, add a crontab job via ansible to run the go program every evening at 8pm.
