# Tasks file for dad jokes
---
- name: "Update cache & Full system update"
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true

- name: Ensure group "gpgroup" exists
  group:
    name: gpgroup
    state: present

- name: Add the user "gpuser"  
  user:
    name: gpuser
    state: present
    comment: General Purpose User
    group: gpgroup

# - name: Add go to .profile for gpuser
#   copy: 
#     src: gpuser_profile
#     dest: /home/gpuser/.profile

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install python pip package twilio
  pip:
    name: twilio

- name: create scripts dir
  file: 
    name: /home/gpuser/scripts
    state: directory
    owner: gpuser
    group: gpgroup
    mode: '0544'

- name: create scripts/modules dir
  file: 
    name: /home/gpuser/scripts/modules
    state: directory
    owner: gpuser
    group: gpgroup
    mode: '0544'

- name: create scripts/data dir
  file: 
    name: /home/gpuser/scripts/data
    state: directory
    owner: gpuser
    group: gpgroup
    mode: '0544'

- name: create scripts/logs dir
  file: 
    name: /home/gpuser/scripts/logs
    state: directory
    owner: gpuser
    group: gpgroup
    mode: '0544'

- name: create scripts/logs/joke_report.log file
  file: 
    path: /home/gpuser/scripts/logs/joke_report.log
    state: touch
    owner: gpuser
    group: gpgroup
    mode: '0544'

# - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
#   file:
#     path: /etc/foo.conf
#     state: touch
#     mode: u=rw,g=r,o=r

- name: deploy joke_report.py
  copy: 
    src: ../joke_report.py
    dest: /home/gpuser/scripts
    owner: gpuser
    group: gpgroup
    mode: '0544'

- name: deploy scripts/modules/sms.py
  copy: 
    src: ../modules/sms.py
    dest: /home/gpuser/scripts/modules/sms.py
    owner: gpuser
    group: gpgroup
    mode: '0544'

- name: deploy scripts/data/joke_data.json
  copy: 
    src: ../data/joke_data.json
    dest: /home/gpuser/scripts/data/joke_data.json
    owner: gpuser
    group: gpgroup
    mode: '0544'
 
- name: create cronjob
  cron:
    name: "run dad joke program"
    minute: "44"
    hour: "15"
    # minute: "0"
    # hour: "1"
    user: gpuser
    job: "cd ~/scripts;/usr/bin/python3 ./joke_report.py 2>&1 | tee -a ~/scripts/logs/joke_report.log" 
    